version: "3"
services:
  frontend:
    container_name: "frontend"
    build: ./
    ports:
      - "3000:3000"
    command: bash -c "yarn; yarn start"
    volumes:
      - ./:/app
    networks:
      - api-backend
    tty: true

networks:
  api-backend:
    external:
      name: api-backend
